### ISSUE TITLE
Empty LICENSE.md

### ISSUE THREAD

**Issue by TheEvilSkeleton** [gzuidhof/friendly-challenge#2]
The license is empty (https://github.com/gzuidhof/friendly-challenge/blob/master/LICENSE.md), so I assume it's open source, and not free and open source?

**Comment by gzuidhof** [comment]
🤦 Oops.. It definitely is free and open source under a permissive license (MIT)! Added the license now, as well as a guide on how to self host everything end to end.

**Comment by TheEvilSkeleton** [comment]
Awesome and thank you for the quick response, I shall close the issue now
