### ISSUE TITLE
How to fallback to the global endpoint if eu one is not enabeld?

### ISSUE THREAD

**Issue by 92ahmed92** [gzuidhof/friendly-challenge#244]
In my application each customer can create his own account on friendlyCaptcha and choose to enable the eu endpoint or not. 
How can I make my client and server consider first fetching from and verfying on the eu endpoint and then on the global one it the eu endpoint doesn't work?

**Comment by merlinfuchs** [comment]
This should do the trick: https://docs.friendlycaptcha.com/#/eu_endpoint?id=fallback-to-global-service
