### ISSUE TITLE
needs performance improvements for "any-device"

### ISSUE THREAD

**Issue by supervisitor** [gzuidhof/friendly-challenge#4]
like [@jookia](https://github.com/matomo-org/matomo/issues/13905#issuecomment-660759999) , last 2 days I check some devices. From the group of friends of my girlfriend and mine in Switzerland, I found more mobiles like this: Samsung A3, iPhone SE (5), Moto E LTE, Xperia Z5 comp., than the last modern from the major brands (I count 6 of about 50 from the last 10 months). All (without the 6 new!) of this need more than 30 sec., my one, a Galaxy S5 mini with a performance and battery life optimized Android 9 configuration (3-4d alive) needs 46 sec. with Anthony Restaino's Lightning Browser and consumed 1% of battery capacity! 😱
I think you should do some performance improvement work, to serve this users as a good experience too. 😇

**Comment by gzuidhof** [comment]
Thank you for taking the time to do this!

I think the first step for me is to decrease the default difficulty, I will decrease it by approximately 60%. This also makes it twice as cheap for attackers, but seeing as there are no known attackers (yet) I think the user experience is more important. The time it takes should decrease by approximately the same amount, making it more bearable for now..

I expect that these phones probably use the slower Javascript fallback solver, I am confident quite a lot of efficiency and speed performance can be squeezed out of this fallback still.

Another alternative way to improve the time it takes is to split the computation across two cores, phones often have multiple cores (but they are much slower than desktop CPUs).

**Comment by gzuidhof** [comment]
It's live now, could you perhaps try https://friendlycaptcha.com/demo on your device? It should be (on average) 61.45% faster.

If anyone is reading this issue, knows low level Javascript well, the majority of time spent in the fallback solver is in adding 64 bit numbers. Javascript has no 64 bit integers, so instead every 64 bit number is represented as two 32bit numbers. [This is the code that will benefit from optimization the most](https://github.com/gzuidhof/friendly-pow/blob/master/src/blake2b/blake2b.ts#L82-L170). There are multiple ways to do this addition, for sure my method is not the fastest around.

**Comment by supervisitor** [comment]
... exact 30 sec. less: 16 sec.; this is about 65% faster! 😎

**Comment by gzuidhof** [comment]
I'm closing this issue, I think it's acceptable for old devices right now :). Of course always happy to see speedups contributed still.

**Comment by wwahammy** [comment]
@gzuidhof it might be worth looking at/importing [BigInteger.js](https://github.com/peterolson/BigInteger.js/blob/master/BigInteger.js). I don't know offhand of their implementation is any better but at least it's not you having to do it from scratch.
