### ISSUE TITLE
Data attribute data-start="none" does not work.

### ISSUE THREAD

**Issue by jamapag** [gzuidhof/friendly-challenge#6]
Data attribute data-start="none" does not work.
I set:
`<div class="frc-captcha" data-sitekey="KEY" data-start="none"></div>`
And solver starting as soon as I focus on form.

I think this line should be modified, because it doesn't matter what I set to data-start because this.opts.startMode ist set to 'focus' by default:
https://github.com/gzuidhof/friendly-challenge/blob/bb333579fd2e814ab96d14a6a94c24718fe4f559/src/captcha.ts#L71

**Comment by gzuidhof** [comment]
Ah yes, you're right, the case for none needs to be explicitly checked.

I can pick this up end of next week, or I can accept a PR before then. Thank you!

**Comment by gzuidhof** [comment]
Solved in release 0.6.0 👍 

Thank you
