### ISSUE TITLE
Expose delete() or clean() method on widget

### ISSUE THREAD

**Issue by robinvdvleuten** [gzuidhof/friendly-challenge#7]
I'm using the widget on a Next.js powered website. And I noticed that the widget re-creates a worker each time the page containing the form is visited. It would be nice to be able to clean up or delete the widget instance whenever the page is destroyed. Something like;

```js
import { useEffect, useRef } from "react"
import { WidgetInstance } from 'friendly-challenge'

const FriendlyCaptcha = ({ className, puzzleEndpoint, startMode = 'focus', ...rest }) => {
  const container = useRef()
  const widget = useRef()

  useEffect(() => {
    if (!widget.current && container.current) {
      widget.current = new WidgetInstance(container.current, { puzzleEndpoint, startMode })
    }

    return () => {
      // Destroy the widget as the component is unmounting...
	  widget.current.destroy()
      widget.current = null
    }
  }, [container])

  return <div ref={container} className="frc-captcha" {...rest} />
}

export default FriendlyCaptcha
```

**Comment by gzuidhof** [comment]
I agree, it makes sense to have that. I'll put it on the backlog, thank you!

I remember when implementing some very old browsers would actually crash if I deleted the webworker right after it was done, but I'm sure a workaround is possible for that. Relevant line https://github.com/gzuidhof/friendly-challenge/blob/master/src/captcha.ts#L201

**Comment by gzuidhof** [comment]
Come to think of it.. I would expect that the worker gets cleaned up after there is no more reference to it, I guess I was wrong

Until there is some sort of dispose method, you can call `widget.worker.terminate()` manually.

**Comment by gzuidhof** [comment]
In version 0.6.0 a `destroy()` method is now present that cleans up the widget entirely :). Also, it now explicitly terminates workers after the work is done. Let me know if you run into any issues!
